name: deploy

on:
  push:
   branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        with:
          ref: main
      - name: Use Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Setup Hexo Dependencies
        run: |
          npm i -g hexo-cli
          npm install
      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Config Git Infomation
        run: |
          git config --global user.name "YotrolZ" 
          git config --global user.email "674317983@qq.com"
      - name: Deploy Hexo
        env:
          TZ: Asia/Shanghai
        run: |
          hexo clean
          hexo generate 
          hexo deploy
          gulp