name: deploy

on:
  push:
   branches:
    - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        with:
          ref: hexo
      - name: Use Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Setup Hexo Dependencies
        run: |
          npm i -g hexo-cli
          npm install
      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sed -i "s/<token>/${HEXO_DEPLOY_PRI}/g" ./_config.yml
      - name: Config Git Infomation
        run: |
          git config user.name "YotrolZ" 
          git config user.email "674317983@qq.com"
      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate 
          hexo deploy